version: '2'
services:
  hakaze:
    image: python:3.8
    restart: unless-stopped
    env_file: .env
    working_dir: /app
    volumes:
        - python_modules:/usr/local/lib/python3.8
        - ./hakaze:/app/hakaze
        - ./requirements.txt:/app/requirements.txt
    command: bash -c "pip install -r requirements.txt && uvicorn hakaze.server:app --host 0.0.0.0 --port 80"
  imgproxy:
    restart: unless-stopped
    depends_on:
        - nginx
    image: willnorris/imageproxy
    ports:
        - "5001:8080"
    command:
      - "-addr"
      - "0.0.0.0:8080"
      - "-baseURL"
      - "http://nginx/vault/"
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${VAULT_ROOT}:/usr/share/nginx/html/vault:ro
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
        - 27017:27017
    volumes:
        - mongo_data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
volumes:
    mongo_data:
    python_modules:
