version: '2'
services:
  hakaze:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    env_file: .env
  imgproxy:
    restart: unless-stopped
    image: willnorris/imageproxy
    command:
      - "-addr"
      - "0.0.0.0:8080"
      - "-baseURL"
      - "http://vault.sasuga.link:880/"
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      # TODO: this could be copied instead of mounted but eeeh
      - ./client/dist:/usr/share/nginx/html:ro
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/vault:/vault
