version: '2'
services:
  hakaze:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    env_file: .env
  imgproxy:
    restart: unless-stopped
    depends_on:
        - vault
    image: willnorris/imageproxy
    command:
      - "-addr"
      - "0.0.0.0:8080"
      - "-baseURL"
      - "http://vault/"
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    depends_on:
        - imgproxy
    ports:
      - "5000:80"
    volumes:
      # TODO: this could be copied instead of mounted but eeeh
      - ./client/dist:/usr/share/nginx/html:ro
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - d:/vault:/vault
  vault:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - d:/vault:/usr/share/nginx/html:ro
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
        - 27017:27017
    volumes:
        - mongo_data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
volumes:
    mongo_data:
