version: '2'
services:
  hakaze:
    image: python:3.8
    restart: unless-stopped
    env_file: .env.docker
    working_dir: /app
    volumes:
        - python_modules:/usr/local/lib/python3.8
        - ./hakaze:/app/hakaze
        - ./requirements.txt:/app/requirements.txt
        - ${VAULT_ROOT}:/vault
        - ./db:/app/db
        - ../shared/panda:/app/panda
    command: bash -c "pip install -r requirements.txt &&  python -m uvicorn hakaze.server:app --host 0.0.0.0 --port 80"
  imgproxy:
    restart: unless-stopped
    depends_on:
        - nginx
    image: willnorris/imageproxy
    ports:
        - "5001:8080"
    command:
      - "-addr"
      - "0.0.0.0:8080"
      - "-baseURL"
      - "http://nginx/vault/"
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${VAULT_ROOT}:/usr/share/nginx/html/vault:ro 
volumes:
    python_modules:
